# Cấu hình cho streamlit-authenticator
# Tham khảo thêm tại: https://github.com/mkhorasani/Streamlit-Authenticator

# --- CREDENTIALS ---
# Nơi lưu trữ thông tin đăng nhập của người dùng.
# Mật khẩu (password) PHẢI được hash trước khi đưa vào đây.
# Bạn có thể tạo mật khẩu đã hash bằng cách chạy một script riêng sử dụng `stauth.Hasher(['your_password']).generate()`.
credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin
      password: "$2b$12$QXLS7kV/woCCtQ3wagTtke2sNRNXBnEllYADKUjFIEr/fiIjRzJ/u" # Mật khẩu đã được hash
    user:
      email: user@example.com
      name: User
      password: "$2b$12$0j.JJorQThnKZeVXC7C5p.7FV7u3lrP9JDf3HAhs6XXGJFh0v2E36" # Mật khẩu đã được hash

# --- COOKIE SETTINGS ---
# Cấu hình cho cookie xác thực được lưu trên trình duyệt của người dùng.
cookie:
  # expiry_days: Số ngày cookie sẽ hết hạn. Đặt là 0 để cookie hết hạn khi đóng trình duyệt.
  expiry_days: 1
  # key: Một chuỗi ký tự bí mật (secret key) dùng để ký và xác thực cookie.
  key: some_signature_key 
  # name: Tên của cookie sẽ được lưu trong trình duyệt.
  name: some_cookie_name

# --- PREAUTHORIZED ---
# Dành cho các tính năng đăng ký hoặc khôi phục mật khẩu trong tương lai.
# Hiện tại, trong ứng dụng này, mục này chưa được sử dụng trực tiếp.
preauthorized:
  emails:
  - phongvu2010@gmail.com
